version: "3.8"

services:
  demo-gallery-nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    restart: unless-stopped
